### PR TITLE
Compact templating code

### PR DESCRIPTION
**Pull request by vide**
Hello

here again with the same PR, I'm really sorry for all the noise created. This already passes all the tests

### CODE REVIEW

**Comment by mcanevet** [comment]
@cjeanneret could you take a look at this please?

**Comment by vide** [comment]
Yes, please :) I've another PR after this one is merged (cause it already includes this fix), with a new feature

**Comment by raphink** [comment]
Lgtm, it's rather simple and the tests cover it well

**Comment by vide** [comment]
Hello, @cjeanneret ?

**Comment by cjeanneret** [comment]
yup, good for me, merged. Thank you!

**Pull request merged**
