### PR TITLE
Hiera & ENC

### PR DESCRIPTION
**Pull request by GabrielRF**
Making the module compatible with Hiera and External Node Classifiers

### CODE REVIEW

**Comment by raphink** [comment]
This is profile-level stuff imo. I'm not in favor of merging this in a component module.

**Comment by GabrielRF** [comment]
I believe these changes make the module better for people who uses Hiera and The Foreman (ENC), like me, and don't change anything for people who don't. This way the module is able to assist a wider public.

**Comment by mcanevet** [comment]
Even when using foreman you should IMHO have a profiles classes that calls component modules

**Comment by GabrielRF** [comment]
I'm not sure if I understood it correctly, but I'll work on it. :)

**Pull request closed without merging**
