### PR TITLE
use a more terse template code

### PR DESCRIPTION
**Pull request by vide**
Use an Array() cast and always do the same instead of checking if it's an array and acting consequently

### CODE REVIEW

**Comment by cjeanneret** [comment]
Hello,

Unfortunately, the unit-test fails on this new PR:
https://travis-ci.org/camptocamp/puppet-bind/jobs/54236943#L2308

Would be great if you could correct either the template code, or the unit-test content.

Thank you!

**Comment by vide** [comment]
Mmmmh I cannot see the travis build error, the link points to a blank page. Maybe because I've just rebased the PR to include similiar changes to the master zone template?

**Comment by cjeanneret** [comment]
Possible — you might check the overall build status here: https://travis-ci.org/camptocamp/puppet-bind

**Comment by vide** [comment]
It was a problem with my Firefox ;) Ok, fixed the spec after removing some spaces (I kinda prefer this indentation anyway), now the build passes 100%

**Comment by vide** [comment]
Sorry for the mess with the new feature implementation in master, my bad, I shouldn't have merged it so soon. I reverted the commit

**Comment by vide** [comment]
Sorry, I'll redo everything in branches, I just messed it up with git/github. Sorry

**Pull request closed without merging**
